<?php
use PHPMailer\PHPMailer\PHPMailer;
require('../vendor/autoload.php');


if(isset($_POST['email'],$_POST['message'])){
    $email = $_POST['email'];
    $message = $_POST['message'];
    


$mail = new PHPMailer();

   $mail->SMTPOptions = array(
       'ssl' => array(
       'verify_peer' => false,
       'verify_peer_name' => false,
       'allow_self_signed' => true
       )
       );
   $mail->isSMTP();
   $mail->SMTPDebug=0;
   $mail->Host = 'smtp.gmail.com';
   $mail->Port = 587;
   $mail->SMTPSecure =  PHPMailer::ENCRYPTION_STARTTLS;
   $mail->SMTPAuth = true;
   $mail->Username = 'test@maxutraenergy.co.zw'; //set from vc this time
   $mail->Password = '123456]['; //paste one generated by Mailtrap
   $mail->setFrom($email);
   $mail->Subject = 'MAXUTRAE ONLINE SALES';
   $mailContent = $message;
   $mail->Body = $mailContent;
   // $mail->addReplyTo($email, 'Mailtrap');
   $mail->addAddress('test@maxutraenergy.co.zw', 'Maxutrae'); 
   
   $mail->isHTML(true);
   
   
   
   if($mail->send()){
       echo "<script type='text/javascript'>
               alert('Message Send to Client')
               window.location='../admin/order_admin_delivered.php'
               </script>";
      
   }else{
       echo 'Message could not be sent.';
       echo 'Mailer Error: ' . $mail->ErrorInfo;
   }
   

}


?>